name: Profile Metrics - Repositories
on:
  # Schedule daily updates
  schedule: [{cron: "0 2 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches: ["main"]
    paths: ["**metrics-repositories.yml"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: d03n3rfr1tz3
          template: classic
          base: repositories
          config_animations: yes
          config_display: columns
          config_timezone: Europe/Berlin
          plugin_activity: no
          plugin_gists: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_traffic: yes
          
