name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: d03n3rfr1tz3
          template: classic
          base: header, activity, repositories, metadata
          config_animated: yes
          config_timezone: Europe/Berlin
          plugin_achievements: yes
          plugin_activity: no
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0.2%
          plugin_lines: yes
          
