name: Profile Metrics - Other
on:
  # Schedule daily updates
  schedule: [{cron: "0 3/6 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches: ["main"]
    paths: ["**metrics-other.yml"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-other.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: d03n3rfr1tz3
          template: classic
          base: metadata
          config_animations: yes
          config_display: regular
          config_timezone: Europe/Berlin
          plugin_activity: no
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://www.d03n3r.de/
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-other-large.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: d03n3rfr1tz3
          template: classic
          base: metadata
          config_animations: yes
          config_display: large
          config_timezone: Europe/Berlin
          plugin_activity: no
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://www.d03n3r.de/
          
